name: docker-build-and-push

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: devops-training

    steps:
      # 1. Checkout del repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Debug opcional (verifica archivos)
      - name: Debug Dockerfile presence
        run: |
          echo "Listing files in the repo directory"
          ls -al

      # 4. Construir y etiquetar la imagen
      - name: Build Docker Image
        run: |
          docker build \
            -t "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}" \
            .

      # 5. Push a Docker Hub
      - name: Push Docker Image
        run: |
          docker push "${{ vars.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ vars.IMAGE_TAG }}"
